title: "fREW Schmidt's Foolish Manifesto"
author:
  name: "Arthur Axel fREW Schmidt"
  twitter: frioux
indexes:
  tag: 'tags'
baseurl: 'https://blog.afoolishmanifesto.com'
canonifyurls: false
paginate: 50
PygmentsCodeFences: true
