on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update --quiet && sudo apt-get install --quiet --yes libdbd-sqlite3-perl libyaml-syck-perl golang-go
      - run: make init
      - run: make build

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update --quiet && sudo apt-get install --quiet --yes awscli s3cmd libdbd-sqlite3-perl libyaml-syck-perl golang-go
      - run: make init
      - run: cp etc/s3cmd.ini ~/.s3cfg
      - run: make push
        env:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           CF_AUTH_KEY: ${{ secrets.CF_AUTH_KEY }}
           CF_AUTH_EMAIL: ${{ secrets.CF_AUTH_EMAIL }}
